require: rubocop-minitest

AllCops:
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/IfUnlessModifier:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/GuardClause:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/NumericPredicate:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

# only for ruby 2.6+
Style/MapToHash:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/ArgumentAlignment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Minitest/AssertPredicate:
  Enabled: false

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
